"""followers

Revision ID: 18871a216a96
Revises: 946a42a8a5ea
Create Date: 2021-03-12 19:09:33.153165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18871a216a96'
down_revision = '946a42a8a5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
