"""new fields in user model

Revision ID: 946a42a8a5ea
Revises: 69f0d3efe557
Create Date: 2021-03-11 16:39:07.960957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946a42a8a5ea'
down_revision = '69f0d3efe557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
